[server]
maxUploadSize = 2048
maxMessageSize = 2048
enableWebsocketCompression = false
headless = true

[runner]
fastReruns = false

[browser]
gatherUsageStats = false

[theme]
base="light"
primaryColor="#3b82f6"
backgroundColor="#f4f6f9"
secondaryBackgroundColor="#ffffff"
textColor="#1e293b"
font="sans serif"
