[server]
maxUploadSize = 2048
maxMessageSize = 2048
enableWebsocketCompression = false

[runner]
fastReruns = false

[theme]
base = "light"
primaryColor = "#4f46e5"
backgroundColor = "#f8fbff"
secondaryBackgroundColor = "#eef2ff"
textColor = "#111827"
